name: manga_easy_landing_page
description: Pagina sobre o app e download.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  client_driver:
    git:
      url: https://github.com/manga-easy/manga_easy_client_driver.git
      ref: v1.1.2
  get_it: ^7.2.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
# flutter build web --release --web-renderer html --no-tree-shake-icons
