name: manga_easy_landing_page
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  client_driver:
    git:
      url: https://github.com/manga-easy/manga_easy_client_driver.git
      ref: v1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

